name: ticket_system
description: Advanced Ticket Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  intl: ^0.19.0
  flutter_markdown: ^0.6.18
  cached_network_image: ^3.3.0
  file_picker: ^6.1.1
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true